DROP SCHEMA IF EXISTS auth CASCADE;
CREATE SCHEMA auth;

-- Tạo bảng : ACCOUNT
DROP TABLE IF EXISTS auth.ACCOUNT;
CREATE TABLE auth.ACCOUNT
(
  ID SERIAL
, Account VARCHAR(500)
, Password VARCHAR(500)
, Note VARCHAR(500)
);
